### ISSUE TITLE
The OperatorGroup manifest is incorrect. 

### ISSUE THREAD

**Issue by Dimss** [operator-framework/getting-started#40]
The `OperatorGroup` manifest has incorrect indentation for the spec attribute.

*Current*
```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: memcached-operator-group
  namespace: default
  spec:
    targetNamespaces:
    - default
```
*Expected*
```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: memcached-operator-group
  namespace: default
spec:
  targetNamespaces:
  - default
```
